AppVersion: 1.0.0

Server:
  Port: :5555
  Development: true
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5

Kafka:
  Brokers: [ "kafka:9092" ]

Logger:
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

Metrics:
  Port: ":7070"
  Url: "host.docker.internal:7071"
  ServiceName: products_microservice

Jaeger:
  Host: "host.docker.internal:6831"
  ServiceName: products_microservice
  LogSpans: false

MongoDB:
  URI: "mongodb://mongo:27020"
  DB: "service-db"

Redis:
  RedisAddr: "redis:6379"
  RedisPassword:
  RedisDb: 0
  RedisDefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

Http:
  Port: ":5007"
  PprofPort: ":8100"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5