// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"www.github.com/The-iyed/service-example/config"
	"www.github.com/The-iyed/service-example/pkg/kafka"
	"www.github.com/The-iyed/service-example/pkg/logger"
)

// Injectors from wire.go:

func InitKafkaConsumer(cfg *config.Config, log logger.Logger) kafka.IKafkaConsumer {
	iKafkaConsumer := kafka.NewKafkaConsumer(cfg, log)
	return iKafkaConsumer
}

func InitKafkaProducer(cfg *config.Config, log logger.Logger) kafka.IKafkaProducer {
	iKafkaProducer := kafka.NewKafkaProducer(cfg, log)
	return iKafkaProducer
}
